const hardcodedCourses = [
  {
    id: 1,
    name: "Pebble Beach Golf Links",
    club: "Pebble Beach Golf Club",
    country: "USA",
    address: "1700 17-Mile Drive, Pebble Beach, CA",
  },
  {
    id: 2,
    name: "St. Andrews Old Course",
    club: "St. Andrews Links",
    country: "Scotland",
    address: "St Andrews, Scotland",
  },
  {
    id: 3,
    name: "Augusta National Golf Club",
    club: "Augusta National",
    country: "USA",
    address: "2604 Washington Rd, Augusta, GA",
  },
  {
    id: 4,
    name: "Royal Troon Golf Club",
    club: "Royal Troon",
    country: "Scotland",
    address: "Troon, Scotland",
  },
  {
    id: 5,
    name: "Pine Valley Golf Club",
    club: "Pine Valley",
    country: "USA",
    address: "1 E Atlantic Ave, Pine Valley, NJ",
  },
  {
    id: 6,
    name: "Cypress Point Club",
    club: "Cypress Point",
    country: "USA",
    address: "3150 17 Mile Dr, Pebble Beach, CA",
  },
  {
    id: 7,
    name: "Shinnecock Hills Golf Club",
    club: "Shinnecock Hills",
    country: "USA",
    address: "200 Tuckahoe Rd, Southampton, NY",
  },
  {
    id: 8,
    name: "Muirfield",
    club: "The Honourable Company of Edinburgh Golfers",
    country: "Scotland",
    address: "Duncur Rd, Gullane, Scotland",
  },
  {
    id: 9,
    name: "Oakmont Country Club",
    club: "Oakmont",
    country: "USA",
    address: "1233 Hulton Rd, Oakmont, PA",
  },
  {
    id: 10,
    name: "Royal Melbourne Golf Club",
    club: "Royal Melbourne",
    country: "Australia",
    address: "Cheltenham Rd, Black Rock, VIC",
  },
  {
    id: 11,
    name: "Ballybunion Golf Club",
    club: "Ballybunion",
    country: "Ireland",
    address: "Sandhill Rd, Ballybunion, Co. Kerry",
  },
  {
    id: 12,
    name: "Carnoustie Golf Links",
    club: "Carnoustie",
    country: "Scotland",
    address: "Links Parade, Carnoustie, Scotland",
  },
  {
    id: 13,
    name: "Royal County Down Golf Club",
    club: "Royal County Down",
    country: "Northern Ireland",
    address: "36 Golf Links Rd, Newcastle, Co. Down",
  },
  {
    id: 14,
    name: "Turnberry (Ailsa)",
    club: "Turnberry",
    country: "Scotland",
    address: "Maidens Rd, Turnberry, Scotland",
  },
  {
    id: 15,
    name: "Kingston Heath Golf Club",
    club: "Kingston Heath",
    country: "Australia",
    address: "Kingston Rd, Cheltenham, VIC",
  },
  {
    id: 16,
    name: "Royal Portrush Golf Club",
    club: "Royal Portrush",
    country: "Northern Ireland",
    address: "Dunluce Rd, Portrush, Co. Antrim",
  },
  {
    id: 17,
    name: "Winged Foot Golf Club",
    club: "Winged Foot",
    country: "USA",
    address: "851 Fenimore Rd, Mamaroneck, NY",
  },
  {
    id: 18,
    name: "Sunningdale Golf Club",
    club: "Sunningdale",
    country: "England",
    address: "Ridgemount Rd, Sunningdale, Ascot",
  },
  {
    id: 19,
    name: "Royal Birkdale Golf Club",
    club: "Royal Birkdale",
    country: "England",
    address: "Waterloo Rd, Southport",
  },
  {
    id: 20,
    name: "Whistling Straits",
    club: "Whistling Straits",
    country: "USA",
    address: "N8501 Lakeshore Rd, Sheboygan, WI",
  },
  {
    id: 21,
    name: "Bethpage Black",
    club: "Bethpage State Park",
    country: "USA",
    address: "99 Quaker Meeting House Rd, Farmingdale, NY",
  },
  {
    id: 22,
    name: "Kiawah Island (Ocean)",
    club: "Kiawah Island Golf Resort",
    country: "USA",
    address: "1 Sanctuary Beach Dr, Kiawah Island, SC",
  },
  {
    id: 23,
    name: "Bandon Dunes",
    club: "Bandon Dunes Golf Resort",
    country: "USA",
    address: "57744 Round Lake Rd, Bandon, OR",
  },
  {
    id: 24,
    name: "Cabot Cliffs",
    club: "Cabot Links",
    country: "Canada",
    address: "18 Cabot Lane, Inverness, NS",
  },
  {
    id: 25,
    name: "Royal St George's Golf Club",
    club: "Royal St George's",
    country: "England",
    address: "Golf Rd, Sandwich",
  },
  {
    id: 26,
    name: "Merion Golf Club",
    club: "Merion",
    country: "USA",
    address: "450 Ardmore Ave, Ardmore, PA",
  },
  {
    id: 27,
    name: "Seminole Golf Club",
    club: "Seminole",
    country: "USA",
    address: "901 Seminole Blvd, Juno Beach, FL",
  },
  {
    id: 28,
    name: "Sand Hills Golf Club",
    club: "Sand Hills",
    country: "USA",
    address: "36410 Sand Hills Rd, Mullen, NE",
  },
  {
    id: 29,
    name: "Fishers Island Club",
    club: "Fishers Island",
    country: "USA",
    address: "PO Box 605, Fishers Island, NY",
  },
  {
    id: 30,
    name: "National Golf Links of America",
    club: "National Golf Links",
    country: "USA",
    address: "149 Sebonac Inlet Rd, Southampton, NY",
  },
  {
    id: 31,
    name: "Chicago Golf Club",
    club: "Chicago Golf Club",
    country: "USA",
    address: "25W253 Warrenville Rd, Wheaton, IL",
  },
  {
    id: 32,
    name: "Los Angeles Country Club (North)",
    club: "Los Angeles Country Club",
    country: "USA",
    address: "10101 Wilshire Blvd, Los Angeles, CA",
  },
  {
    id: 33,
    name: "Riviera Country Club",
    club: "Riviera",
    country: "USA",
    address: "1250 Capri Dr, Pacific Palisades, CA",
  },
  {
    id: 34,
    name: "Spyglass Hill Golf Course",
    club: "Spyglass Hill",
    country: "USA",
    address: "3206 Stevenson Dr, Pebble Beach, CA",
  },
  {
    id: 35,
    name: "TPC Sawgrass (Stadium)",
    club: "TPC Sawgrass",
    country: "USA",
    address: "110 Championship Way, Ponte Vedra Beach, FL",
  },
  {
    id: 36,
    name: "Quaker Ridge Golf Club",
    club: "Quaker Ridge",
    country: "USA",
    address: "146 Griffen Ave, Scarsdale, NY",
  },
  {
    id: 37,
    name: "Baltusrol Golf Club (Lower)",
    club: "Baltusrol",
    country: "USA",
    address: "201 Shunpike Rd, Springfield, NJ",
  },
  {
    id: 38,
    name: "Oak Hill Country Club (East)",
    club: "Oak Hill",
    country: "USA",
    address: "346 Kilbourn Rd, Rochester, NY",
  },
  {
    id: 39,
    name: "The Country Club",
    club: "The Country Club",
    country: "USA",
    address: "191 Clyde St, Chestnut Hill, MA",
  },
  {
    id: 40,
    name: "Medinah Country Club (No. 3)",
    club: "Medinah",
    country: "USA",
    address: "6N001 Medinah Rd, Medinah, IL",
  },
];

export default hardcodedCourses;
